language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
- pip install --upgrade pip
- pip install .[test]
- pip install .[doc]

services:
  - docker

sudo: required
  
before_install:
  - sudo sysctl -w vm.max_map_count=262144
  - make deps-up-d
  - sudo apt-get update -qq

script: make test-with-manual-deps

deploy:
  - provider: script
    script: make docker-build && make docker-tag && make docker-push
    on:
      all_branches: true
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASS
    distributions: sdist bdist_wheel
    on:
      repo: USGS-EROS/lcmap-blackmagic
      branch: master

notifications:
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd 

