version: "3"

services:

  #blackmagic-cassandra:
  #  container_name: blackmagic-cassandra
  #  image: cassandra:3.9
  #  network_mode: "host"

  blackmagic-nginx:
    container_name: blackmagic-nginx
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./nginxcache:/data/nginx/cache:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  blackmagic-localstack:
    container_name: blackmagic-localstack
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      #- SERVICES=${SERVICES- }
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"